### ISSUE TITLE
App\Sock\Parser\WebSock::encode(string $raw, $client, $commandBean)  多一个参数$commandBean

### ISSUE THREAD

**Issue by lxk310** [octopuszy/LTalk-swoole#2]
Fatal error: Declaration of App\Sock\Parser\WebSock::encode(string $raw, $client, $commandBean): ?string must be compatible with EasySwoole\Core\Socket\AbstractInterface\ParserInterface::encode(string $raw, $client): ?string

**Comment by octopuszy** [comment]
感谢反馈，明天一早我调试一下给您答复

**Comment by octopuszy** [comment]
由于 es 最近频繁更新，导致代码不适配，我已将v1.0版本固定到es的 v2.0.2，后续版本会跟上 es 最新改动，感谢反馈
